# Generated by Django 6.0.3 on 2026-04-10 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_categories_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name_categories',
            field=models.CharField(max_length=200, verbose_name='Назва категорії'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='categories', to='notes.note', verbose_name='Нотатки'),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Виконано'),
        ),
        migrations.AlterField(
            model_name='note',
            name='reminder',
            field=models.BooleanField(default=False, verbose_name='Нагадування'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
    ]
